version: 2.1

orbs:
  github-cli: circleci/github-cli@2.5.0
  maven: circleci/maven@2.0.0
  aws-cli: circleci/aws-cli@4.1.3
  win: circleci/windows@5.0.0

jobs:
  build-jar:
    docker:
      - image: cimg/openjdk:11.0.25
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Build Client Jar
          command: |
            chmod +x gradlew
            ./gradlew clean build
      - run:
          name: Extract Version
          command: |
            VERSION=$(ls build/libs/launcher-*.jar | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+-SNAPSHOT')
            echo "export JAR_VERSION=$VERSION" >> $BASH_ENV
            source $BASH_ENV
            echo "Detected version: $JAR_VERSION"
      - run:
          name: Generate InnoSetup file
          command: |
            ./gradlew filterInnosetup
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/RuneLite.jar
            - build/filtered-resources/kraken64.iss
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches

  build-windows-exe:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install InnoSetup
          command: |
            $url = "https://jrsoftware.org/download.php/is.exe"
            $output = "innosetup.exe"
            Invoke-WebRequest -Uri $url -OutFile $output
            
            Start-Process -FilePath $output -ArgumentList "/SILENT" -Wait
            
            $env:PATH += ";C:\Program Files (x86)\Inno Setup 6"
            echo $env:PATH
      - run:
          name: Build Windows Executable
          command: |
            cd build/filtered-resources
            & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" kraken64.iss
            Get-ChildItem -Recurse -Name "*.exe"
      - persist_to_workspace:
          root: .
          paths:
            - build/filtered-resources/Output/KrakenSetup.exe
      - store_artifacts:
          path: "build/filtered-resources/Output/KrakenSetup.exe"

  deploy:
    docker:
      - image: cimg/openjdk:11.0.25
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install MinIO Client
          command: |
            curl -fsSL https://dl.min.io/client/mc/release/linux-amd64/mc -o /tmp/mc
            chmod +x /tmp/mc
            sudo mv /tmp/mc /usr/local/bin/mc
            mc --version
      - run:
          name: Configure MinIO Client
          command: |
            mc alias set s3 $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
      - run:
          name: Upload to MinIO
          command: |
            # Optionally update a "latest" version
            mc cp build/filtered-resources/Output/KrakenSetup.exe s3/kraken-bootstrap-static/KrakenSetup.exe

workflows:
  build-and-deploy:
    jobs:
      - build-jar:
          context:
            - Kraken Env
      - build-windows-exe:
          requires:
            - build-jar
          context:
            - Kraken Env
      - deploy:
          requires:
            - build-jar
            - build-windows-exe
          context:
            - Kraken Env
          filters:
            branches:
              only:
                - main
                - master