/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kraken;

import org.junit.Test;
import static org.junit.Assert.*;

public class KrakenLauncherTest {
    @Test public void appHasAGreeting() {
        org.example.App classUnderTest = new org.example.App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
